### ISSUE TITLE
das-cli --version is printing wrong version number

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-toolbox#118]
See error log below:

```
$ sudo das-cli update-version
Updating the package das-cli...
Package version successfully updated  0.4.0 --> 0.4.1.
$ das-cli --version
das-cli 0.4.0 
```

The same behavior if updated using apt-get:

```
$ sudo apt-get install das-cli
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  bridge-utils dctrl-tools dkms gconf2 libatomic1:i386 libbsd0:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386
  libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386 libffi8:i386 libflashrom1
  libftdi1-2 libgl1:i386 libgl1-mesa-dri:i386 libglapi-mesa:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386
  libicu70:i386 libllvm13 libllvm13:i386 libllvm15:i386 libmd0:i386 libnvidia-common-515 libnvidia-common-525
  libnvidia-common-535 libnvidia-egl-wayland1 libnvidia-extra-515 libnvidia-extra-525 libnvidia-extra-535
  libnvidia-fbc1-515 libnvidia-fbc1-515:i386 libnvidia-fbc1-525 libnvidia-fbc1-525:i386 libnvidia-fbc1-535
  libnvidia-fbc1-535:i386 libnvidia-gl-515 libnvidia-gl-515:i386 libnvidia-gl-525 libnvidia-gl-525:i386 libnvidia-gl-535
  libnvidia-gl-535:i386 libpciaccess0:i386 libsensors5:i386 libstdc++6:i386 libvulkan1:i386 libwayland-client0:i386
  libx11-6:i386 libx11-xcb1:i386 libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386
  libxcb-randr0:i386 libxcb-shm0:i386 libxcb-sync1:i386 libxcb-xfixes0:i386 libxcb1:i386 libxdmcp6:i386 libxext6:i386
  libxfixes3:i386 libxml2:i386 libxnvctrl0 libxshmfence1:i386 libxxf86vm1:i386 mesa-vulkan-drivers:i386
  nvidia-firmware-535-535.171.04 nvidia-settings pkg-config screen-resolution-extra ubuntu-fan
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  das-cli
0 upgraded, 1 newly installed, 0 to remove and 98 not upgraded.
Need to get 14.5 MB of archives.
After this operation, 14.8 MB of additional disk space will be used.
Get:1 http://45.77.4.33/apt-repo stable/main amd64 das-cli amd64 0.4.1 [14.5 MB]
Fetched 14.5 MB in 3s (4,585 kB/s)  
Selecting previously unselected package das-cli.
(Reading database ... 255871 files and directories currently installed.)
Preparing to unpack .../das-cli_0.4.1_amd64.deb ...
Unpacking das-cli (0.4.1) ...
Setting up das-cli (0.4.1) ...
Processing triggers for man-db (2.10.2-1) ...
$ das-cli --version
das-cli 0.4.0
```

**Comment by levisingularity** [comment]
@andre-senna The `das-cli` has a file called [`src/common/config.py`](https://github.com/singnet/das-toolbox/blob/master/src/config/config.py) that contains a constant named `VERSION`. This constant stores the version of `das-cli`, and when we run `das-cli --version`, the CLI is simply printing this version to the user. The reason for using this constant instead of fetching the version from the deb package is that the user might not be using `das-cli` through the deb package.

The deb package version is generated during the pipeline, so it's always synchronized with the tag number created on GitHub. When we use the release script, it automatically updates the version in this file, ensuring that both the file version and the pipeline version are in sync. However, if someone manually generates the version in the pipeline and forgets to update the file, it results in a mismatch, with the deb package showing one version and the CLI displaying another.

As far as I can tell, this isn’t a bug. The last PR that generated a new version for `das-cli` didn’t update the `VERSION` in the config file, so it was likely a manual deployment where this step was overlooked. We can either think of another approach to handle this or ensure that all deployments are done through the scripts to avoid this issue.

**Comment by andre-senna** [comment]
@levisingularity 

OK. I agree it's not a bug. Please make sure we provide proper guidance for this in our guidelines document in the `das` repo. Please make this documentation fix before closing this issue.
